# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='describtion',
            new_name='description',
        ),
    ]
